export type ValidPathname =
  | "/"
  | "/login"
  | "/(tabs)"
  | "/(tabs)/"
  | "/(tabs)/account"
  | "/_sitemap"
  | "/account"
  | "/profile"
  | "/register"
  | "/address"
  | "/paymentsMethods"
  | "/orders"
  | "/status"
  | "/cart"
  | `./${string}`
  | `../${string}`
  | ".."
  | `${string}:${string}`;
